name: 'Install Enso Build'
description: 'Installs enso-build tool.'
inputs:
  clean:
    description: Whether the local build script repository should be cleaned.
    required: true
    default: 'false'
  ref:
    description: Reference of the ci-build repository to use.
    required: true
    default: 'deployed'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        clean: ${{ inputs.clean }}
        path: ci-build
        ref: ${{ inputs.ref }}
        repository: enso-org/ci-build

    - name: Setup conda
      uses: s-weigand/setup-conda@v1.0.5
      if: startsWith(runner.name, 'GitHub Actions') # GitHub-hosted runner.
      with:
        update-conda: false
        conda-channels: anaconda, conda-forge

    # Runs a set of commands using the runners shell
    - uses: actions/github-script@v6
      with:
        script: |
          console.warn(process.env)
          core.addPath(String.raw`${{ runner.temp }}/bin`);
          await exec.exec('cargo', ['install', '--root', String.raw`${{ runner.temp }}`, '--bins', '--path', './build'], {'cwd': String.raw`${{ github.workspace }}/ci-build`});
          core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
          core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])
          core.exportVariable("GITHUB_RETENTION_DAYS", process.env["GITHUB_RETENTION_DAYS"])
