pull_request_rules:
- name: Automatic merge on approval
  conditions:
  - "label=CI: Ready to merge"
  actions:
    merge:
      method: squash
      commit_message_template: |
          {{ title }}
      
          {{ body | get_section("### Commit Message", "") }}

- name: Automatic PR update
  conditions:
  - "label=CI: Ready to merge"
  actions:
      update:
