[workspace]

members = [
    "lib/rust/ast",
    "lib/rust/enso-data",
    "lib/rust/enso-generics",
    "lib/rust/enso-logger",
    "lib/rust/enso-macro-utils",
    "lib/rust/enso-optics",
    "lib/rust/enso-prelude",
    "lib/rust/enso-shapely/impl",
    "lib/rust/enso-shapely/macros",
    "lib/rust/flexer",
    "lib/rust/flexer-testing/definition",
    "lib/rust/flexer-testing/generation",
    "lib/rust/launcher-shims",
    "lib/rust/lazy-reader",
    "lib/rust/lexer/definition",
    "lib/rust/lexer/generation",
    "lib/rust/parser",
]

[profile.dev]
opt-level        = 0
lto              = false
debug            = true
debug-assertions = true

[profile.release]
opt-level        = 3
lto              = true
debug            = false
panic            = 'abort'
debug-assertions = false

[profile.bench]
opt-level        = 3
lto              = true
debug            = false
debug-assertions = false

[profile.test]
opt-level        = 0
lto              = false
debug            = true
debug-assertions = true
