name: Release CI

on:
  push:
    tags:
      - "fast-*"

env:
  # Please ensure that this is in sync with graalVersion in build.sbt
  graalVersion: 21.1.0
  # Please ensure that this is in sync with javaVersion in build.sbt
  javaVersion: 11
  # Please ensure that this is in sync with project/build.properties
  sbtVersion: 1.5.2
  # Please ensure that this is in sync with rustVersion in build.sbt
  rustToolchain: nightly-2021-05-12

concurrency: "releases"

jobs:
  create-release:
    name: Prepare Release
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_REF }}
          release_name: Enso ${{ env.GITHUB_REF }}
          body: "Please fill-in the release description"
          draft: true
          prerelease: true

      # Upload the assets to the created release
      - name: Publish a file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: repo/build.sbt
          asset_name: build.sbt
          asset_content_type: text/plain
