name: Nightly Release CI

env:
  # Specifies how many nightly releases should be kept. Any older releases are removed.
  NIGHTLIES_TO_KEEP: 20

concurrency: "releases"

on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 4 * * 2-6" # 4am (UTC) from Tuesday to Saturday (i.e. after every workday)
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: [self-hosted]
    outputs:
      ENSO_VERSION: ${{ steps.prepare-step.outputs.ENSO_VERSION }}
      ENSO_RELEASE_ID: ${{ steps.prepare-step.outputs.ENSO_RELEASE_ID }}
    steps:
#      - uses: actions/checkout@v2
#        with:
#          clean: false
#          path: ci-build
#          ref: develop
#          repository: enso-org/ci-build
      - uses: actions/checkout@v2
        with:
          path: enso
      - uses: ./enso/action
        with:
          ref: develop
          target: enso
          command: "--kind nightly prepare"


  #      - name: Run a multi-line script
#        id: prepare-step
#        run: cargo run --bin enso-build -- ../enso --kind nightly prepare
#        working-directory: ${{ github.workspace }}/ci-build
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

  finish:
    runs-on: [self-hosted]
    needs: [prepare, build]
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          path: ci-build
          ref: develop
          repository: enso-org/ci-build
      - uses: actions/checkout@v2
        with:
          path: enso
      - uses: actions/github-script@v5
        with:
          script: |
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])
            core.exportVariable("GITHUB_RETENTION_DAYS", process.env["GITHUB_RETENTION_DAYS"])
      - name: Run a multi-line script
        id: prepare-step
        run: cargo run --bin enso-build -- ../enso --kind nightly finish
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTEFACT_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTEFACT_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1


  build:
    needs: prepare
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [macos-latest]
          - [self-hosted, Windows, engine]
          - [self-hosted, Linux, engine]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          path: enso
      - uses: ./enso/action
        with:
          ref: develop
          target: enso
          command: "--kind nightly upload"
