name: Release CI

on:
  tags:
    - 'enso-*.*.*'

jobs:
  build:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Pretend build
        shell: bash
        run: echo ${{ runner.os }} > release.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: enso-${{ runner.os }}
          path: release.txt
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      # Without specifying options, it downloads all artifacts
      - uses: actions/download-artifact@v2
        path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: "Please fill in the release description"
      #     draft: true
      #     prerelease: true

